### ISSUE TITLE
Player count hover seems to have "...and ## more..." text when there are a certain number of whitelisted players on the server

### ISSUE THREAD

**Issue by axemwa** [KennyTV/Maintenance#28] opened 2019-04-02 10:20 UTC
## Bug reproducibility
**How does the problem occur/what are the steps to reproduce it?**
Occurs when either a certain amount of players are whitelisted and on the server
or,
if there are fakeplayers/bots added to the server who are usually always on
I am using [BotMaker](https://www.spigotmc.org/resources/botmaker.64909/) plugin which could potentially be the main cause for this but it's possible that it's doing it for multiple players whitelisted as well but I only have a limited number of accounts to test that theory with
## Error
No errors

## Server information
**Type '/maintenance dump' and paste the given link here**
https://hasteb.in/ocefiyan

Image of issue below
![image](https://user-images.githubusercontent.com/37608633/55395225-a98cc900-5588-11e9-8591-cb8a59c3905e.png)

Originally reported in discussions on spigot
https://www.spigotmc.org/threads/maintenancemode-bungee-and-spigot-support-1-8-1-13.239576/page-8#post-3347363

**Comment by KennyTV** [comment] 2019-04-02 12:15
I reproduced the issue with the BotMaker plugin, but the text seems to be coming from the plugin itself - when I removed the ping listener of BotMaker, the `... and x more ...` disappeared.
For that, set `startup.fake-slots` to false in their config (though that will obviously display the playercount without the fakeplayers when maintenance is disabled).

Does the message also show up when there are more than ~15 players **without** Botmaker?

**Comment by axemwa** [comment] 2019-04-02 15:25
I gathered botmaker would be doing that, as for whether it does this for real players I'm not sure as my server isn't technically public yet. Maybe you can ask a user of your plugin that has a server of 10 or more real players on it to test it out for you?

**Comment by axemwa** [comment] 2019-04-03 09:23
To test it you would have to get someone who uses it to add at least 10 real players to their whitelist if their server has more than 10 players on, I dont know anyone who uses this plugin though that does fall under those conditions

**Comment by KennyTV** [comment] 2019-05-17 15:30
I'm 99% certain this won't happen (unless some other plugin changes the ping, too), so I'm going to close this 👀

**Closed by KennyTV** 2019-05-17 15:30 UTC

**Comment by axemwa** [comment] 2019-05-18 03:50
No worries yeah I think it's BotMaker causing it too, so I reported it to them to see if they will fix it ;P
